; Script generated by Antigravity for GrewAnalytics Setup
#define MyAppName "GrewAnalytics"
#define MyAppVersion "2.4"
#define MyAppPublisher "Grew Energy Private Limited"
#define MyAppExeName "GrewAnalytics.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={{5A8E192B-0F88-43C6-BA2E-5A1DDF0E53CC}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName}
AppPublisher={#MyAppPublisher}
; Default installation folder dynamically resolved by [Code] below
DefaultDirName={code:GetDefaultDirName}
PrivilegesRequired=lowest
UninstallFilesDir={app}\uninst
UsePreviousPrivileges=no
UsePreviousAppDir=no
DisableDirPage=no
DisableProgramGroupPage=yes
DefaultGroupName={#MyAppName}
; Refuse to install while the app is running (launcher creates this mutex)
AppMutex=GrewAnalyticsAppMutex
CloseApplications=yes
UninstallDisplayIcon={app}\{#MyAppExeName}
VersionInfoVersion={#MyAppVersion}
; Set output folder and filename (outputs Setup directly to D:\GrewAnalytics)
OutputDir=D:\GrewAnalytics
OutputBaseFilename=GrewAnalytics Setup
SetupIconFile=Logo.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[InstallDelete]
; Wipe the payload dir on upgrade so files removed between versions don't linger
Type: filesandordirs; Name: "{app}\_internal"

[Files]
Source: "dist_staging\dist\GrewAnalytics\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{userdesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function GetDefaultDirName(Param: String): String;
begin
  if DirExists('D:\') then
    Result := 'D:\GrewAnalytics'
  else
    Result := ExpandConstant('{localappdata}\GrewAnalytics');
end;
