CREATE TABLE "revenue" (
	"Invoice date" date,
	"Invoice Type" varchar(255),
	"Invoice No" varchar(255),
	"Cust_code" varchar(255),
	"Cust_name" varchar(255),
	"WP" varchar(255),
	"Brand Code" varchar(255),
	"Mat Desc" varchar(255),
	"SalesQty" bigint,
	"UnitPrice ₹" bigint,
	"Value" bigint,
	"Invoice value" bigint,
	"UOM" varchar(255),
	"Plant" varchar(255),
	"Storage Location" varchar(255),
	"Vehicle No." varchar(255),
	"S.O.Number" varchar(255),
	"Incoterms" varchar(255),
	"Invoice Status" varchar(255),
	"Segment" varchar(255),
	"MW" varchar(255),
	"Month" varchar(255),
	"Year" varchar(255),
	"Week" varchar(255),
	"Time Index" varchar(255),
	"Month2" varchar(255),
	"tag" varchar(255),
	"Revenue" varchar(255),
	"Sales Head" varchar(255),
	"EWAY BILL DATE." varchar(255),
	"EWAY Expiry" varchar(255)
);
