import { pgTable, varchar, date, bigint } from 'drizzle-orm/pg-core';

export const revenue = pgTable('revenue', {
    invoiceDate: date('Invoice date'),
    invoiceType: varchar('Invoice Type', { length: 255 }),
    invoiceNo: varchar('Invoice No', { length: 255 }),
    custCode: varchar('Cust_code', { length: 255 }),
    custName: varchar('Cust_name', { length: 255 }),
    wp: varchar('WP', { length: 255 }),
    brandCode: varchar('Brand Code', { length: 255 }),
    matDesc: varchar('Mat Desc', { length: 255 }),
    salesQty: bigint('SalesQty', { mode: 'number' }),
    unitPrice: bigint('UnitPrice ₹', { mode: 'number' }),
    value: bigint('Value', { mode: 'number' }),
    invoiceValue: bigint('Invoice value', { mode: 'number' }),
    uom: varchar('UOM', { length: 255 }),
    plant: varchar('Plant', { length: 255 }),
    storageLocation: varchar('Storage Location', { length: 255 }),
    vehicleNo: varchar('Vehicle No.', { length: 255 }),
    soNumber: varchar('S.O.Number', { length: 255 }),
    incoterms: varchar('Incoterms', { length: 255 }),
    invoiceStatus: varchar('Invoice Status', { length: 255 }),
    segment: varchar('Segment', { length: 255 }),
    mw: varchar('MW', { length: 255 }),
    month: varchar('Month', { length: 255 }),
    year: varchar('Year', { length: 255 }),
    week: varchar('Week', { length: 255 }),
    timeIndex: varchar('Time Index', { length: 255 }),
    month2: varchar('Month2', { length: 255 }),
    tag: varchar('tag', { length: 255 }),
    revenue: varchar('Revenue', { length: 255 }),
    saleshead: varchar('Sales Head', { length: 255 }),
    ewayBillDate: varchar('EWAY BILL DATE.', { length: 255 }),
    ewayExpiry: varchar('EWAY Expiry', { length: 255 })
});
